baseURL = "https://open-rtls.com/"
title = "Open RTLS"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
timeZone = "Europe/Berlin"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  siteDescription = "Open RTLS provides open source building blocks for RTLS-enabled applications."
  ogImage = "/images/open-rtls-logo.svg"
  formationUrl = "https://tryformation.com/"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1

[permalinks.page]
  "pages" = "/:slugorcontentbasename/"

[build]
  noJSConfigInAssets = false

[minify]
  disableCSS = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS"]
